spring.application.name=auction-service
server.port=8081
spring.datasource.url=${AUCTION_DB_URL:jdbc:mysql://localhost:3306/auction_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC}
spring.datasource.username=${AUCTION_DB_USERNAME:root}
spring.datasource.password=${AUCTION_DB_PASSWORD:root}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jackson.time-zone=UTC
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
