import { Link, useParams } from 'react-router-dom'
import { useCallback, useEffect, useState } from 'react'
import { getAuctionActivity, getAuctionById } from '../services/auctionService'
import { getAuctionSummary, getBids, getRankings, getSuppliers, submitBid } from '../services/bidService'
import { apiErrorMessage, formatCurrency, toIso, toLocalInputValue } from '../utils/formatters'
import ActivityLog from '../components/activity/ActivityLog'
import AuctionInfo from '../components/auction/AuctionInfo'
import Countdown from '../components/auction/Countdown'
import BidHistory from '../components/bids/BidHistory'
import { ErrorState, LoadingState } from '../components/common/PageState'
import RankingTable from '../components/ranking/RankingTable'

const initialBid = () => ({ supplierId: '', freightCharges: '', originCharges: '0', destinationCharges: '0', transitTimeDays: '', quoteValidUntil: toLocalInputValue(Date.now() + 86400000) })
function Section({ title, children }) { return <section><h2 className="mb-3 text-lg font-semibold text-slate-900">{title}</h2>{children}</section> }

export default function AuctionDetailsPage() {
  const { id } = useParams(); const [data, setData] = useState(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [form, setForm] = useState(initialBid); const [submitError, setSubmitError] = useState(''); const [submitting, setSubmitting] = useState(false)
  const load = useCallback(async () => { setLoading(true); setError(''); try { const [auction, activity, bids, rankings, summary, suppliers] = await Promise.all([getAuctionById(id), getAuctionActivity(id), getBids(id), getRankings(id), getAuctionSummary(id), getSuppliers()]); setData({ auction, activity, bids, rankings, summary, suppliers }) } catch (err) { setError(apiErrorMessage(err)) } finally { setLoading(false) } }, [id])
  const refreshAuction = useCallback(async () => { try { const auction = await getAuctionById(id); setData((current) => current ? { ...current, auction } : current) } catch (err) { setError(apiErrorMessage(err)) } }, [id])
  useEffect(() => { load() }, [load])
  const update = (event) => setForm({ ...form, [event.target.name]: event.target.value })
  const bid = async (event) => { event.preventDefault(); setSubmitError(''); const freight = Number(form.freightCharges); const origin = Number(form.originCharges || 0); const destination = Number(form.destinationCharges || 0); const transit = Number(form.transitTimeDays); if (!form.supplierId || !form.freightCharges || !form.transitTimeDays || !form.quoteValidUntil) return setSubmitError('Complete all required fields.'); if (transit <= 0) return setSubmitError('Transit time must be greater than zero.'); if (freight + origin + destination <= 0) return setSubmitError('Total bid must be greater than zero.'); setSubmitting(true); try { await submitBid({ auctionId: id, supplierId: form.supplierId, freightCharges: freight, originCharges: origin, destinationCharges: destination, transitTimeDays: transit, quoteValidUntil: toIso(form.quoteValidUntil) }); setForm(initialBid()); await load() } catch (err) { setSubmitError(apiErrorMessage(err)) } finally { setSubmitting(false) } }
  if (loading) return <LoadingState label="Loading auction details…" />; if (error) return <ErrorState message={error} onRetry={load} />
  const { auction, activity, bids, rankings, summary, suppliers } = data; const active = auction.state === 'ACTIVE'; const supplierName = (supplierId) => suppliers.find((supplier) => supplier.id === supplierId)?.name || supplierId
  return <><Link to="/" className="mb-5 inline-block text-sm font-medium text-blue-700">← All auctions</Link><div className="grid gap-5 lg:grid-cols-[1fr_280px]"><div className="space-y-8"><AuctionInfo auction={auction} /><Section title="Supplier rankings"><div className="mb-3 rounded-xl border border-emerald-200 bg-emerald-50 p-4"><p className="text-xs font-semibold uppercase tracking-wide text-emerald-700">Current L1</p><p className="mt-1 text-xl font-bold text-emerald-900">{summary.supplierId ? `${supplierName(summary.supplierId)} · ${formatCurrency(summary.currentLowestBid)}` : 'No bids yet'}</p></div><RankingTable rankings={rankings} supplierName={supplierName} /></Section><Section title="Bid history"><BidHistory bids={bids} supplierName={supplierName} /></Section><Section title="Activity log"><ActivityLog activity={activity} /></Section></div><aside className="space-y-5"><Countdown closeTime={auction.currentCloseTime} active={active} onExpired={refreshAuction} /><div className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-semibold">Extension configuration</h2><dl className="mt-4 space-y-3 text-sm"><div className="flex justify-between"><dt className="text-slate-500">Trigger window</dt><dd>{auction.triggerWindowMinutes} min</dd></div><div className="flex justify-between"><dt className="text-slate-500">Extension duration</dt><dd>{auction.extensionDurationMinutes} min</dd></div></dl></div><form onSubmit={bid} className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-semibold">Submit bid</h2>{submitError && <p className="mt-3 rounded bg-rose-50 p-2 text-xs text-rose-700">{submitError}</p>}<fieldset disabled={!active || submitting} className="mt-4 space-y-3"><select required name="supplierId" value={form.supplierId} onChange={update} className="input w-full"><option value="">Supplier *</option>{suppliers.filter((supplier) => supplier.active).map((supplier) => <option key={supplier.id} value={supplier.id}>{supplier.name}</option>)}</select>{[['freightCharges', 'Freight charges *', '0'], ['originCharges', 'Origin charges', '0'], ['destinationCharges', 'Destination charges', '0'], ['transitTimeDays', 'Transit days *', '1']].map(([field, placeholder, min]) => <input key={field} required={field === 'freightCharges' || field === 'transitTimeDays'} min={min} step={field === 'transitTimeDays' ? '1' : '0.01'} type="number" name={field} value={form[field]} onChange={update} placeholder={placeholder} className="input w-full" />)}<input required type="datetime-local" name="quoteValidUntil" value={form.quoteValidUntil} onChange={update} className="input w-full" /><button className="w-full rounded-md bg-blue-700 px-3 py-2 text-sm font-semibold text-white disabled:bg-slate-300">{submitting ? 'Submitting…' : active ? 'Submit bid' : 'Auction not accepting bids'}</button></fieldset></form></aside></div></>
}
